# Generated by Django 3.0.3 on 2020-07-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booknum',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='stockavail',
            field=models.CharField(max_length=100),
        ),
    ]
