# Generated by Django 3.0.3 on 2020-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200713_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='noc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='booknum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='stockavail',
            field=models.IntegerField(),
        ),
    ]
